Models/GenreViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MovieApp.Entity;

namespace MovieApp.Models
{
    public class GenreViewModel
    {
        [Required(ErrorMessage = "Zorunlu Alan")]
        [Display(Name = "Tür Adı")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "3-20 karakter arası olmalı")]
        public string GenreName { get; set; }
        public List<GenreModel> Genres { get; set; }
    }
    public class GenreModel
    {
        public int GenreId { get; set; }
        [Display(Name = "Tür Adı")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "3-20 karakter arası olmalı")]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string GenreName { get; set; }
        public int Count { get; set; }
    }

    public class GenreEditModel
    {
        public int GenreId { get; set; }
        [Display(Name = "Tür Adı")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "3-20 karakter arası olmalı")]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string GenreName { get; set; }
        public List<MovieViewModel> Movies { get; set; }
    }
}

Models/MovieViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MovieApp.Entity;

namespace MovieApp.Models
{
    public class MovieViewModels
    {
        public List<MovieViewModel> Movies { get; set; }
    }
    public class MovieViewModel
    {
        public int MovieId { get; set; }
        [Display(Name = "Film Adı")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "3-20 karakter arası olmalı")]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        [Display(Name = "Film Açıklaması")]
        [StringLength(2000, MinimumLength = 3, ErrorMessage = "3-2000 karakter arası olmalı")]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string Description { get; set; }
        public string fragmentUrl { get; set; }
        public string RunningTime { get; set; }
        public string Imdb { get; set; }
        public string Quality { get; set; }
        public DateTime ReleaseYear { get; set; }
        public bool IsHome { get; set; }
        public bool IsSlayder { get; set; }
        public List<Genre> Genres { get; set; }

        [Required(ErrorMessage = "Zorunlu Alan")]
        public int[] GenreIds { get; set; }
    }
    public class MovieEditViewModel
    {
        public int MovieId { get; set; }
        [Display(Name = "Film Adı")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "3-20 karakter arası olmalı")]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        [Display(Name = "Film Açıklaması")]
        [StringLength(2000, MinimumLength = 3, ErrorMessage = "3-2000 karakter arası olmalı")]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string Description { get; set; }
        //public List<Genre> SelectedGenres { get; set; }
        [Required(ErrorMessage = "Zorunlu Alan")]
        public int[] GenreIds { get; set; }

        public string fragmentUrl { get; set; }
        public string RunningTime { get; set; }
        public string Imdb { get; set; }
        public string Quality { get; set; }
        public DateTime ReleaseYear { get; set; }
        public bool IsHome { get; set; }
        public bool IsSlayder { get; set; }

        public List<Genre> Genres { get; set; }
    }

}

Controllers/AdminController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieApp.Entity;
using MovieApp.Models;

namespace MovieApp.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private UserManager<User> _userManager;
        private SignInManager<User> _signInManager;
        public AdminController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(model.UserName);
                if (user == null)
                {
                    ModelState.AddModelError("", "Bu Kullanıcı Mevcut Değil");
                    return View(model);
                }
                var result = await _signInManager.PasswordSignInAsync(user, model.Password, false, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Movie");
                }

            }
            ModelState.AddModelError("", "Bilinmeyen Bir Hata Oluştu");
            return View(model);
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(UserModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User()
                {
                    Name = model.Name,
                    UserName = model.UserName,
                    Email = model.Email,
                    Password = model.Password,
                    RePassword = model.RePassword

                };

                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Movie");
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/GenreController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieApp.Data;
using MovieApp.Entity;
using MovieApp.Models;

namespace MovieApp.Controllers
{
     [Authorize]
    public class GenreController : Controller
    {
        private readonly MovieContext _context;
        public GenreController(MovieContext context)
        {
            _context = context;
        }
        private GenreViewModel GetGenres()
        {
            return new GenreViewModel
            {
                Genres = _context.Genres.Select(a => new GenreModel
                {
                    GenreId = a.Id,
                    GenreName = a.Name,
                    Count = a.Movies.Count
                }).ToList()
            };
        }
        public IActionResult Index()
        {
            ViewBag.Count = _context.Genres.Count();
            return View(GetGenres());
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var entity = _context.Genres.Select(i => new GenreEditModel
            {
                GenreId = i.Id,
                GenreName = i.Name,
                Movies = i.Movies.Select(a => new MovieViewModel
                {
                    MovieId = a.MovieId,
                    Name = a.Name,
                    ImageUrl = a.ImageUrl
                }).ToList()
            }).FirstOrDefault(i => i.GenreId == id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(GenreEditModel model, int[] MovieIds)
        {
            if (ModelState.IsValid)
            {
                if (model == null)
                {
                    return NotFound();
                }
                var entity = _context.Genres.Include("Movies").FirstOrDefault(i => i.Id == model.GenreId);
                entity.Name = model.GenreName;
                foreach (var id in MovieIds)
                {
                    entity.Movies.Remove(entity.Movies.FirstOrDefault(i => i.MovieId == id));
                }
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(model);

        }
        public IActionResult GenreDelete(int? genreId)
        {
            var entity = _context.Genres.Find(genreId);
            if (entity != null)
            {
                _context.Genres.Remove(entity);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult GenreCreate(GenreViewModel model)
        {
            // if (model.GenreName != null && model.GenreName.Length < 3 || model.GenreName.Length > 20)
            // {
            //     ModelState.AddModelError("GenreName", "3-20 karakter arasi olmalı");
            // }
            if (ModelState.IsValid)
            {
                // var entity = new Genre
                // {
                //     Name = model.GenreName
                // };

                _context.Genres.Add(new Genre { Name = model.GenreName });
                _context.SaveChanges();
            }
            return View("Index", GetGenres());

        }
    }
}

Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieApp.Data;
using MovieApp.Entity;
using MovieApp.Models;

namespace MovieApp.Controllers
{
     [Authorize]
    public class MovieController : Controller
    {
        private readonly MovieContext _context;
        public MovieController(MovieContext context)
        {
            _context = context;
        }

        public IActionResult Index(string q)
        {
            // film ve tur tablosunu dahil ederiz
            var m = _context.Movies
            .Include(a => a.Genres)
            .Select(m => new MovieViewModel
            {
                MovieId = m.MovieId,
                Name = m.Name,
                Description = m.Description,
                ImageUrl = m.ImageUrl,
                Genres = m.Genres.ToList()
            }).AsQueryable();//sonraki işlemleri yapabilmek için asqueryable olması lazım


            if (!string.IsNullOrWhiteSpace(q))
            {
                m = m.Where(i => i.Name.ToLower().Contains(q.ToLower()) || i.Description.ToLower().Contains(q.ToLower()));
            }
            return View(m.ToList());
        }
        [HttpGet]
        public IActionResult Create()
        {
            //genre bilgilerini alip viewde select olarak gösterir
            ViewBag.Genres = _context.Genres.ToList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(MovieViewModel model, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                var entity = new Movie
                {

                    Name = model.Name,
                    Description = model.Description,
                    ImageUrl = "no_image.png",
                    Imdb = model.Imdb,
                    fragmentUrl = model.fragmentUrl,
                    Quality = model.Quality,
                    RunningTime = model.RunningTime,
                    IsHome = model.IsHome,
                    IsSlayder = model.IsSlayder,
                    ReleaseYear = model.ReleaseYear
                };


                foreach (var id in model.GenreIds)
                {
                    entity.Genres.Add(_context.Genres.FirstOrDefault(i => i.Id == id));
                }
                if (file != null)
                {
                    var extension = Path.GetExtension(file.FileName);
                    var fileName = string.Format($"{Guid.NewGuid()}{extension}");
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", fileName);
                    model.ImageUrl = fileName;
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
                _context.Movies.Add(entity);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Genres = _context.Genres.ToList();
            return View(model);
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var entity = _context.Movies
                .Select(a => new MovieEditViewModel
                {
                    MovieId = a.MovieId,
                    Name = a.Name,
                    Description = a.Description,
                    ImageUrl = a.ImageUrl,
                    Imdb = a.Imdb,
                    fragmentUrl = a.fragmentUrl,
                    Quality = a.Quality,
                    RunningTime = a.RunningTime,
                    IsHome = a.IsHome,
                    IsSlayder = a.IsSlayder,
                    ReleaseYear = a.ReleaseYear,
                    GenreIds = a.Genres.Select(i => i.Id).ToArray()
                }).FirstOrDefault(i => i.MovieId == id);
            if (entity == null)
            {
                return NotFound();
            }
            //genre bilgilerini alip viewde select olarak gösterir
            ViewBag.Genres = _context.Genres.ToList();

            return View(entity);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(MovieEditViewModel model, int[] GenreIds, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                var entity = _context.Movies.Include(i => i.Genres).FirstOrDefault(i => i.MovieId == model.MovieId);
                if (entity == null)
                {
                    return NotFound();
                }

                entity.MovieId = model.MovieId;
                entity.Name = model.Name;
                entity.Description = model.Description;
                entity.fragmentUrl = model.fragmentUrl;
                entity.Imdb = model.Imdb;
                entity.IsHome = model.IsHome;
                entity.IsSlayder = model.IsSlayder;
                entity.ReleaseYear = model.ReleaseYear;
                entity.RunningTime = model.RunningTime;
                entity.Quality = model.Quality;


                //parametre olarak aldiğimiz id lere karşilik gelen idleri atariz
                entity.Genres = model.GenreIds.Select(id => _context.Genres.FirstOrDefault(i => i.Id == id)).ToList();
                if (file != null)
                {
                    var extension = Path.GetExtension(file.FileName);
                    var fileName = string.Format($"{Guid.NewGuid()}{extension}");
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", fileName);
                    entity.ImageUrl = fileName;
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.Genres = _context.Genres.ToList();
            return View(model);

        }
        public IActionResult Details(int id)
        {
            var m = _context.Movies
                        .Where(i => i.MovieId == id)
                        .Include(a => a.Genres)
                        .FirstOrDefault();

            return View(m);
        }
        public IActionResult MovieDelete(int? MovieId)
        {
            var entity = _context.Movies.Find(MovieId);

            if (entity != null)
            {
                _context.Remove(entity);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

ViewComponents/CategoryMenuViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;

namespace MovieApp.ViewComponents
{
    public class GenreViewComponent : ViewComponent
    {
        private readonly MovieContext _context;
        public GenreViewComponent(MovieContext context)
        {
            _context = context;
        }
        public IViewComponentResult Invoke()
        {

            ViewBag.SelectedCategory = RouteData?.Values["id"];

            return View(_context.Genres.ToList());
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Movie App</title>
	<!-- Tell the browser to be responsive to screen width -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="/AdminTheme/plugins/fontawesome-free/css/all.min.css">
	<!-- Ionicons -->
	<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	<!-- Tempusdominus Bbootstrap 4 -->
	<link rel="stylesheet" href="/AdminTheme/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
	<!-- iCheck -->
	<link rel="stylesheet" href="/AdminTheme/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
	<!-- JQVMap -->
	<link rel="stylesheet" href="/AdminTheme/plugins/jqvmap/jqvmap.min.css">
	<!-- Theme style -->
	<link rel="stylesheet" href="/AdminTheme/dist/css/adminlte.min.css">
	<!-- overlayScrollbars -->
	<link rel="stylesheet" href="/AdminTheme/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
	<!-- Daterange picker -->
	<link rel="stylesheet" href="/AdminTheme/plugins/daterangepicker/daterangepicker.css">
	<!-- summernote -->
	<link rel="stylesheet" href="/AdminTheme/plugins/summernote/summernote-bs4.css">
	<!-- Google Font: Source Sans Pro -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini layout-fixed">
	<div class="wrapper">


		<!-- Main Sidebar Container -->
		<aside class="main-sidebar sidebar-dark-primary elevation-4">
			<!-- Brand Logo -->
			<a href="index3.html" class="brand-link">
				<img src="/AdminTheme/dist/img/AdminLTELogo.png" alt="AdminLTE Logo"
					class="brand-image img-circle elevation-3" style="opacity: .8">
				<span class="brand-text font-weight-light">Admin Panel</span>
			</a>

			<!-- Sidebar -->
			<div class="sidebar">
				<!-- Sidebar user panel (optional) -->
				<div class="user-panel mt-3 pb-3 mb-3 d-flex">
					<div class="image">
						<img src="/AdminTheme/dist/img/user2-160x160.jpg" class="img-circle elevation-2"
							alt="User Image">
					</div>
					<div class="info">
						<a href="#" class="d-block">Ömer Uyghur</a>
					</div>
				</div>

				<!-- Sidebar Menu -->
				<nav class="mt-2">
					<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
						data-accordion="false">
						<!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

						<li class="nav-item has-treeview">
							<a href="#" class="nav-link">
								<i class="nav-icon fas fa-copy"></i>
								<p>
									Türler
									<i class="fas fa-angle-left right"></i>
									<span class="badge badge-info right">6</span>
								</p>
							</a>
							<ul class="nav nav-treeview">
								<li class="Genre/Index">
									<a href="/Genre/Index" class="nav-link">
										<i class="far fa-circle nav-icon"></i>
										<p>Türler Listesi</p>
									</a>
								</li>

							</ul>
						</li>

						<li class="nav-item has-treeview">
							<a href="#" class="nav-link">
								<i class="nav-icon fas fa-copy"></i>
								<p>
									Filmler
									<i class="fas fa-angle-left right"></i>
									<span class="badge badge-info right">6</span>
								</p>
							</a>
							<ul class="nav nav-treeview">
								<li class="nav-item">
									<a href="/Movie/Index" class="nav-link">
										<i class="far fa-circle nav-icon"></i>
										<p>Filmler Listesi</p>
									</a>
								</li>
								<li class="nav-item">
									<a href="/Movie/Create" class="nav-link">
										<i class="far fa-circle nav-icon"></i>
										<p>Film Ekle</p>
									</a>
								</li>

							</ul>
						</li>
						<li class="nav-item">
							<a href="/Admin/Index" class="nav-link">
								<i class="nav-icon fas fa-th"></i>
								<p>
									Admin
								</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="/Admin/Logout" class="nav-link">
								<i class="nav-icon fas fa-th"></i>
								<p>
									Çıkış
								</p>
							</a>
						</li>

					</ul>
				</nav>
				<!-- /.sidebar-menu -->
			</div>
			<!-- /.sidebar -->
		</aside>

		<!-- Content Wrapper. Contains page content -->
		<div class="content-wrapper">
			<!-- Content Header (Page header) -->
			<div class="container">
				@RenderBody()
			</div>
		</div>

		<!-- Control Sidebar -->
		<aside class="control-sidebar control-sidebar-dark">
			<!-- Control sidebar content goes here -->
		</aside>
		<!-- /.control-sidebar -->
	</div>
	<!-- ./wrapper -->

	<!-- jQuery -->
	<script src="/AdminTheme/plugins/jquery/jquery.min.js"></script>
	<!-- jQuery UI 1.11.4 -->
	<script src="/AdminTheme/plugins/jquery-ui/jquery-ui.min.js"></script>
	<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
	<script>
		$.widget.bridge('uibutton', $.ui.button)
	</script>
	<!-- Bootstrap 4 -->
	<script src="/AdminTheme/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
	<!-- ChartJS -->
	<script src="/AdminTheme/plugins/chart.js/Chart.min.js"></script>
	<!-- Sparkline -->
	<script src="/AdminTheme/plugins/sparklines/sparkline.js"></script>
	<!-- JQVMap -->
	<script src="/AdminTheme/plugins/jqvmap/jquery.vmap.min.js"></script>
	<script src="/AdminTheme/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
	<!-- jQuery Knob Chart -->
	<script src="/AdminTheme/plugins/jquery-knob/jquery.knob.min.js"></script>
	<!-- daterangepicker -->
	<script src="/AdminTheme/plugins/moment/moment.min.js"></script>
	<script src="/AdminTheme/plugins/daterangepicker/daterangepicker.js"></script>
	<!-- Tempusdominus Bootstrap 4 -->
	<script src="/AdminTheme/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
	<!-- Summernote -->
	<script src="/AdminTheme/plugins/summernote/summernote-bs4.min.js"></script>
	<!-- overlayScrollbars -->
	<script src="/AdminTheme/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
	<!-- AdminLTE App -->
	<script src="/AdminTheme/dist/js/adminlte.js"></script>
	<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
	<script src="/AdminTheme/dist/js/pages/dashboard.js"></script>
	<!-- AdminLTE for demo purposes -->
	<script src="/AdminTheme/dist/js/demo.js"></script>
	@RenderSection("scripts",false)
</body>

</html>

Views/Shared/_genre.cshtml
@foreach (var item in Model.Genres)
{
    <li class="header__nav-item">
        <a class="header__nav-link" href="#" role="button">@item.Name</a>
    </li>
}

Views/Shared/_movie.cshtml
@model IEnumerable<Movie>
<!-- card -->
@foreach (var item in Model)
{
    <div class="col-6 col-sm-12 col-lg-6">
        <div class="card card--list">
            <div class="row">
                <div class="col-12 col-sm-4">
                    <div class="card__cover">
                        <img src="~/img/@item.ImageUrl" alt="">
                        <a href="#" class="card__play">
                            <i class="icon ion-ios-play"></i>
                        </a>
                    </div>
                </div>

                <div class="col-12 col-sm-8">
                    <div class="card__content">
                        <h3 class="card__title"><a asp-controller="Home" asp-action="Details"
                            asp-route-id="@item.MovieId">@item.Name</a></h3>
                        <span class="card__category">
                            <a href="#">Action</a>
                            <a href="#">Triler</a>
                        </span>

                        <div class="card__wrap">
                            <span class="card__rate"><i class="icon ion-ios-star"></i>8.4</span>

                            <ul class="card__list">
                                <li>HD</li>
                                <li>16+</li>
                            </ul>
                        </div>

                        <div class="card__description">
                            <p>@Html.Raw(item.Description) </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<!-- end card -->

Views/Shared/_navbar.cshtml
<style>
	.header__auth {
		margin-right: 45px;
	}
</style>
<!-- header -->
<header class="header">
	<div class="header__wrap">

		<div class="row">
			<div class="col-12">
				<div class="header__content">
					<!-- header logo -->
					<a href="/" class="header__logo">
						<img src="/Template/img/logo.svg" alt="">
					</a>
					<!-- end header logo -->

					<!-- header nav -->
					<ul class="header__nav">
						<!-- dropdown -->

						@await Component.InvokeAsync("Genre")
						<!-- end dropdown -->

						<!-- dropdown -->
						@* <li class="dropdown header__nav-item">
							<a class="dropdown-toggle header__nav-link header__nav-link--more" href="#" role="button"
							id="dropdownMenuMore" data-toggle="dropdown" aria-haspopup="true"
							aria-expanded="false"><i class="icon ion-ios-more"></i></a>

							<ul class="dropdown-menu header__dropdown-menu" aria-labelledby="dropdownMenuMore">
							<li><a href="/Movie/Index">Admin</a></li>
							<li><a href="signin.html">Sign In</a></li>
							<li><a href="signup.html">Sign Up</a></li>
							<li><a href="404.html">404 Page</a></li>
							</ul>
							</li> *@
						<!-- end dropdown -->
					</ul>
					<!-- end header nav -->

					<!-- header auth -->
					<div class="header__auth">
						<button class="header__search-btn" type="button">
							<i class="icon ion-ios-search"></i>
						</button>
						@if (User.Identity.IsAuthenticated)
						{
							<a asp-controller="Admin" asp-action="Logout" class="header__sign-in">
								<i class="icon ion-ios-log-in"></i>
								<span>Logout</span>
							</a>
						}
						else
						{
							<a asp-controller="Admin" asp-action="Login" class="header__sign-in">
								<i class="icon ion-ios-log-in"></i>
								<span>Login</span>
							</a>
						}

					</div>
					<!-- end header auth -->


				</div>
			</div>

		</div>
	</div>

	<!-- header search -->
	<form action="#" class="header__search">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="header__search-content">
						<input type="text" name="q" placeholder="Search for a movie">
						<button type="submit" value="submit">search</button>
					</div>
				</div>
			</div>
		</div>
	</form>
	<!-- end header search -->
</header>