Models/GenreViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MovieApp.Entity;

namespace MovieApp.Models
{
    public class GenreViewModel
    {
        [Required(ErrorMessage = "Zorunlu Alan")]
        [Display(Name = "Tür Adı")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "3-20 karakter arası olmalı")]
        public string GenreName { get; set; }
        public List<GenreModel> Genres { get; set; }
    }
    public class GenreModel
    {
        public int GenreId { get; set; }
        [Display(Name = "Tür Adı")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "3-20 karakter arası olmalı")]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string GenreName { get; set; }
        public int Count { get; set; }
    }

    public class GenreEditModel
    {
        public int GenreId { get; set; }
        [Display(Name = "Tür Adı")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "3-20 karakter arası olmalı")]
        [Required(ErrorMessage = "Zorunlu Alan")]
        public string GenreName { get; set; }
        public List<MovieViewModel> Movies { get; set; }
    }
}

Controllers/GenreController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieApp.Data;
using MovieApp.Entity;
using MovieApp.Models;

namespace MovieApp.Controllers
{
     [Authorize]
    public class GenreController : Controller
    {
        private readonly MovieContext _context;
        public GenreController(MovieContext context)
        {
            _context = context;
        }
        private GenreViewModel GetGenres()
        {
            return new GenreViewModel
            {
                Genres = _context.Genres.Select(a => new GenreModel
                {
                    GenreId = a.Id,
                    GenreName = a.Name,
                    Count = a.Movies.Count
                }).ToList()
            };
        }
        public IActionResult Index()
        {
            ViewBag.Count = _context.Genres.Count();
            return View(GetGenres());
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var entity = _context.Genres.Select(i => new GenreEditModel
            {
                GenreId = i.Id,
                GenreName = i.Name,
                Movies = i.Movies.Select(a => new MovieViewModel
                {
                    MovieId = a.MovieId,
                    Name = a.Name,
                    ImageUrl = a.ImageUrl
                }).ToList()
            }).FirstOrDefault(i => i.GenreId == id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(GenreEditModel model, int[] MovieIds)
        {
            if (ModelState.IsValid)
            {
                if (model == null)
                {
                    return NotFound();
                }
                var entity = _context.Genres.Include("Movies").FirstOrDefault(i => i.Id == model.GenreId);
                entity.Name = model.GenreName;
                foreach (var id in MovieIds)
                {
                    entity.Movies.Remove(entity.Movies.FirstOrDefault(i => i.MovieId == id));
                }
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(model);

        }
        public IActionResult GenreDelete(int? genreId)
        {
            var entity = _context.Genres.Find(genreId);
            if (entity != null)
            {
                _context.Genres.Remove(entity);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult GenreCreate(GenreViewModel model)
        {
            // if (model.GenreName != null && model.GenreName.Length < 3 || model.GenreName.Length > 20)
            // {
            //     ModelState.AddModelError("GenreName", "3-20 karakter arasi olmalı");
            // }
            if (ModelState.IsValid)
            {
                // var entity = new Genre
                // {
                //     Name = model.GenreName
                // };

                _context.Genres.Add(new Genre { Name = model.GenreName });
                _context.SaveChanges();
            }
            return View("Index", GetGenres());

        }
    }
}

Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieApp.Data;
using MovieApp.Entity;
using MovieApp.Models;

namespace MovieApp.Controllers
{
     [Authorize]
    public class MovieController : Controller
    {
        private readonly MovieContext _context;
        public MovieController(MovieContext context)
        {
            _context = context;
        }

        public IActionResult Index(string q)
        {
            // film ve tur tablosunu dahil ederiz
            var m = _context.Movies
            .Include(a => a.Genres)
            .Select(m => new MovieViewModel
            {
                MovieId = m.MovieId,
                Name = m.Name,
                Description = m.Description,
                ImageUrl = m.ImageUrl,
                Genres = m.Genres.ToList()
            }).AsQueryable();//sonraki işlemleri yapabilmek için asqueryable olması lazım


            if (!string.IsNullOrWhiteSpace(q))
            {
                m = m.Where(i => i.Name.ToLower().Contains(q.ToLower()) || i.Description.ToLower().Contains(q.ToLower()));
            }
            return View(m.ToList());
        }
        [HttpGet]
        public IActionResult Create()
        {
            //genre bilgilerini alip viewde select olarak gösterir
            ViewBag.Genres = _context.Genres.ToList();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(MovieViewModel model, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                var entity = new Movie
                {

                    Name = model.Name,
                    Description = model.Description,
                    ImageUrl = "no_image.png",
                    Imdb = model.Imdb,
                    fragmentUrl = model.fragmentUrl,
                    Quality = model.Quality,
                    RunningTime = model.RunningTime,
                    IsHome = model.IsHome,
                    IsSlayder = model.IsSlayder,
                    ReleaseYear = model.ReleaseYear
                };


                foreach (var id in model.GenreIds)
                {
                    entity.Genres.Add(_context.Genres.FirstOrDefault(i => i.Id == id));
                }
                if (file != null)
                {
                    var extension = Path.GetExtension(file.FileName);
                    var fileName = string.Format($"{Guid.NewGuid()}{extension}");
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", fileName);
                    model.ImageUrl = fileName;
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
                _context.Movies.Add(entity);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Genres = _context.Genres.ToList();
            return View(model);
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var entity = _context.Movies
                .Select(a => new MovieEditViewModel
                {
                    MovieId = a.MovieId,
                    Name = a.Name,
                    Description = a.Description,
                    ImageUrl = a.ImageUrl,
                    Imdb = a.Imdb,
                    fragmentUrl = a.fragmentUrl,
                    Quality = a.Quality,
                    RunningTime = a.RunningTime,
                    IsHome = a.IsHome,
                    IsSlayder = a.IsSlayder,
                    ReleaseYear = a.ReleaseYear,
                    GenreIds = a.Genres.Select(i => i.Id).ToArray()
                }).FirstOrDefault(i => i.MovieId == id);
            if (entity == null)
            {
                return NotFound();
            }
            //genre bilgilerini alip viewde select olarak gösterir
            ViewBag.Genres = _context.Genres.ToList();

            return View(entity);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(MovieEditViewModel model, int[] GenreIds, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                var entity = _context.Movies.Include(i => i.Genres).FirstOrDefault(i => i.MovieId == model.MovieId);
                if (entity == null)
                {
                    return NotFound();
                }

                entity.MovieId = model.MovieId;
                entity.Name = model.Name;
                entity.Description = model.Description;
                entity.fragmentUrl = model.fragmentUrl;
                entity.Imdb = model.Imdb;
                entity.IsHome = model.IsHome;
                entity.IsSlayder = model.IsSlayder;
                entity.ReleaseYear = model.ReleaseYear;
                entity.RunningTime = model.RunningTime;
                entity.Quality = model.Quality;


                //parametre olarak aldiğimiz id lere karşilik gelen idleri atariz
                entity.Genres = model.GenreIds.Select(id => _context.Genres.FirstOrDefault(i => i.Id == id)).ToList();
                if (file != null)
                {
                    var extension = Path.GetExtension(file.FileName);
                    var fileName = string.Format($"{Guid.NewGuid()}{extension}");
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", fileName);
                    entity.ImageUrl = fileName;
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.Genres = _context.Genres.ToList();
            return View(model);

        }
        public IActionResult Details(int id)
        {
            var m = _context.Movies
                        .Where(i => i.MovieId == id)
                        .Include(a => a.Genres)
                        .FirstOrDefault();

            return View(m);
        }
        public IActionResult MovieDelete(int? MovieId)
        {
            var entity = _context.Movies.Find(MovieId);

            if (entity != null)
            {
                _context.Remove(entity);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Views/Genre/Edit.cshtml
@model GenreEditModel
<style>
    .form-check-input-width:2em;
</style>
@{
    Layout = "_AdminLayout";
}
<h3>Genre Edit Page</h3>
<form asp-controller="Genre" asp-action="Edit" method="post">
    <input type="hidden" name="GenreId" value="@Model.GenreId">
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                <label asp-for="GenreName"></label>
                <input type="text" asp-for="GenreName" class="form-control">
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        <div class="col-md-9">
            @for (int i = 0; i < Model.Movies.Count; i++)
            {
                <input type="hidden" name="Movies[@i].MovieId " value="@Model.Movies[i].MovieId " />
                <input type="hidden" name="Movies[@i].ImageUrl " value="@Model.Movies[i].ImageUrl " />
                <input type="hidden" name="Movies[@i].Name " value="@Model.Movies[i].Name " />
            }
            <table class="table table-bordered table-striped table-hover">
                <thead>
                    <tr>
                        <th style="width: 30px;">Remove</th>
                        <th style="width: 15px;"># </th>
                        <th style="width: 100px;">Image</th>
                        <th>Title</th>
                        <th style="width: 160px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Movies)
                    {
                        <tr>
                            <td>
                                <input class="form-check-input" type="checkbox" name="MovieIds" value="@item.MovieId"
                                style="margin-left: auto;">
                            </td>

                            <td>@item.MovieId</td>
                            <td>
                                <img src="~/img/@item.ImageUrl" width="80" />
                            </td>
                            <td>@item.Name</td>
                            <td>
                                @* <a class="btn btn-sm btn-primary" asp-controller="Movie" asp-action="Edit"
                                    asp-route-id="@item.MovieId">Edit</a> *@

                                <form asp-controller="Movie" asp-action="MovieDelete" method="post"
                                style="display: inline;">
                                    <input type="hidden" name="movieId" value="@item.MovieId">
                                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>

                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</form>

Views/Genre/Index.cshtml
@model GenreViewModel
@{
    Layout = "_AdminLayout";
}
<div class="row">
    <div class="col-md-3 mt-3">
        <h3>Create Genre</h3>
        <hr>
        <form asp-controller="Genre" asp-action="GenreCreate" method="post">
            <div class="form-group">
                <label asp-for="GenreName"></label>
                <input asp-for="GenreName" class="form-control">
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary mt-2">Submit</button>
        </form>
    </div>
    <div class="col-md-9 mt-3">
        <h3>Genre List</h3>
        <hr>
        <div class="row">
            <div class="col-md 12">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th style="width: 30px;">#</th>
                            <th>Name</th>
                            <th style="width: 40px;">Count</th>
                            <th style="width: 160px;"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Genres)
                        {
                            <tr>
                                <td>@item.GenreId</td>
                                <td>@item.GenreName</td>
                                <td>@item.Count</td>
                                <td>
                                    <a class="btn btn-sm btn-primary" asp-controller="Genre" asp-action="Edit"
                                    asp-route-id="@item.GenreId">Edit</a>
                                    <form asp-controller="Genre" asp-action="GenreDelete" style="display: inline;">
                                        <input type="hidden" name="genreId" value="@item.GenreId">
                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>